### ISSUE TITLE
Use a Set and not a Queue

### ISSUE THREAD

**Issue by ErunamoJAZZ** [OsuCelebrity/OsuCelebrity#26]
Hello.

I notice people is spamming to spect some users... I saw the queue with 1000 positions!!. I think, if you use http://docs.oracle.com/javase/7/docs/api/java/util/Set.html you will avoid excessive repetition.

**Comment by Tillerino** [comment]
Kappa

In all seriousness, we're working on keeping the queue shorter, but I'm pretty sure the chosen datastructures are not the problem ^^
