### ISSUE TITLE
Detecting twitch moderators 

### ISSUE THREAD

**Issue by Tillerino** [OsuCelebrity/OsuCelebrity#30]
Detecting chat moderators via IRC is very unreliable. There are supposedly ways to check for moderators via an API, which would be better.

**Comment by RedbackThomson** [comment]
Not sure about how frequently this updates:
http://tmi.twitch.tv/group/user/osucelebrity/chatters

**Comment by RedbackThomson** [comment]
Implemented the ability to do this in [This commit](https://github.com/OsuCelebrity/OsuCelebrity/commit/9851935274c13a2f1cfa05b0edcd2b445d5b1ef7)

**Comment by Tillerino** [comment]
Hooked it up to twitch IRC bot. Ty <3
