### ISSUE TITLE
client reboot command

### ISSUE THREAD

**Issue by Tillerino** [OsuCelebrity/OsuCelebrity#31]
the osu client can get stuck. we need a command to restart it.

**Comment by Tillerino** [comment]
it seems that there is a problem with OBS if we quit the client from the command line. it's not able to pick up the window when it opens again.

**Comment by FYPetro** [comment]
In the OBS, add Game Capture as source, set application to the osu path and click capture mouse cursor. I wonder if this would help?

**Comment by Tillerino** [comment]
Game capture doesn't even pick the client back up when I restart it by hand.

**Comment by FYPetro** [comment]
Hmm... it works for me on v0.656b right now. For cutting edge, you have to update the game capture each time you update because the executable title changes from everyday.

[osu!]: osu!cuttingedge b20151127 is the latest (today)

**Comment by Tillerino** [comment]
how do you quit/start the client?

**Comment by FYPetro** [comment]
Let me try using cmdline

**Comment by FYPetro** [comment]
Yes. it works for cmd in windows. I used X:\osu\osu!.exe to boot osu and taskkill /im osu!.exe to quit

**Comment by FYPetro** [comment]
And I used X:\osu\osu!.exe to restart again. works fine.

**Comment by FYPetro** [comment]
I'm not sure how to update the game capture options using commandline.

**Comment by Tillerino** [comment]
http://www.disposablechat.com/chat/tillerino?password=

**Comment by Tillerino** [comment]
We were able to replicate the problem. This remains open.

**Comment by FYPetro** [comment]
Summary of the best I could get: Enter password after executing this in cmd (does not need to be privileged):

`runas /noprofile /user:<user> <osu!path>'

**Comment by FYPetro** [comment]
`runas /noprofile /user:<user> /savecred <osu!path>`

I get <user> from `net user` since I always forget my user name.

**Comment by Tillerino** [comment]
using osu://spectate url directly instead of through osu!.exe fixes this problem.
