### ISSUE TITLE
Now Playing beatmap ID

### ISSUE THREAD

**Issue by RedbackThomson** [OsuCelebrity/OsuCelebrity#34]
Get the beatmap and beatmapset IDs of the current playing beatmap

**Comment by omkelderman** [comment]
ok, kinda random, but i sorta started looking into this shit and i wanna share my experiences :P

I was like, osu!StreamCompanion has output-options which include song and map id and other meta-data, so did some random testing with stream companion.
Looks like it is very inaccurate with which diff it gets the id from. if i switch diff, output does not change. if i switch from other song to insane diff, it shows meta-data from the easy-diff (the first).
Soo yeah.... looks like whatever stream companion is doing, its not gud enough for what is needed here.

/end of random story

**Comment by FYPetro** [comment]
Also: current gamemode

**Comment by omkelderman** [comment]
oh snap, thats fast :O HYPE :P
