### ISSUE TITLE
osu! private message ban list

### ISSUE THREAD

**Issue by FYPetro** [OsuCelebrity/OsuCelebrity#45]
On twitch or osu!, provide a mod-level command `!ban <osu-name>` such that the specified user cannot: 

1. get `!voted` (twitch error message: `<osu-name> has been banned from osucelebrity`)
2. interact with osucelebrity on osu! (osu! error message: `You have been banned from using osucelebrity. [https://osu.ppy.sh/u/osucelebrity Contact] our developers and moderators for more info.` is sent with a cooldown of 2 minutes)

**Comment by Tillerino** [comment]
There already is !timeout. What's the point of 2)?

**Comment by FYPetro** [comment]
Will osucelebrity ignore all Bancho IRC messages from people that are the target of effective `!timeout` ?
