### ISSUE TITLE
Auto detect silence. 

### ISSUE THREAD

**Issue by FYPetro** [OsuCelebrity/OsuCelebrity#46]
If the osu account of osucelebrity is silenced, OBS will be automatically configured to show the status and remaining time. Helps a lot if we encounter silences once we reach the stage where we go 24/7.

**Comment by Tillerino** [comment]
I think this is the wrong way to approach this. We need to make sure not to get silenced. Tillerinobot has done this successfully for a year now and it's sending a lot more messages.

**Comment by FYPetro** [comment]
I think this will remain open until the silence problem is totally fixed @Tillerino keep up the good work

**Comment by Tillerino** [comment]
Closing this since silences seem to be over.
