### ISSUE TITLE
Implement Moderator Commands

### ISSUE THREAD

**Issue by RedbackThomson** [OsuCelebrity/OsuCelebrity#5]
In the Twitch chat, moderators should be allowed the following commands:

- !wait - Continues to spectate the current player until the !wait command is called again (possibly !unwait)
- !dankset {number} (eg. !dankset 9001) - overrides the current [!dank](https://github.com/RedbackThomson/OsuCelebrity/issues/2) score
- !continue/!go/!unwait - Skips the current player and continues on to the next

**Comment by Tillerino** [comment]
I think we should wait a bit until we see what a good way of controlling the stream would be.
