### ISSUE TITLE
If I want to modify your skin for osu!celebrity, what credit do I have to give?

### ISSUE THREAD

**Issue by TDashDog1** [OsuCelebrity/OsuCelebrity#57]
It's all in the title. I really like the skin you use for osu!celebrity, but I want to make my own version. Should I include a link to the original skin file? To this github page? To the twitch page?

**Comment by TDashDog1** [comment]
Just found in the skin.ini that this is ReesesPuff's skin. Sorry about that.

**Comment by reesebiz** [comment]
Just a heads up that there's no need to give credit. The skin has a lot of re-used elements anyway.
