### ISSUE TITLE
!np profile link includes parenthesis

### ISSUE THREAD

**Issue by reesebiz** [OsuCelebrity/OsuCelebrity#59]
The !np command's link to the user profile includes a parenthesis in the URL.

![fixmepls](https://cloud.githubusercontent.com/assets/12946317/19627979/6143f534-9919-11e6-8cc8-ca9184719f3f.png)

**Comment by omkelderman** [comment]
it kinda is a twitchchat-problem. There is nothing in the code that says "this is a url". So the only solution would be to not put the url in parenthesis or something...

**Comment by omkelderman** [comment]
ok, we could do `[` and `]` (how are these things called in english again? xd) instead of parenthesis. Just checked and twitchchat doesnt add them to the clickable url
