### ISSUE TITLE
updating beatmaps

### ISSUE THREAD

**Issue by Tillerino** [OsuCelebrity/OsuCelebrity#8]
if a beatmap is updated after it has been downloaded and the player who is being spectated is playing a newer version of the map while we still have the older version, spectating won't do anything.

**Comment by FYPetro** [comment]
Since we could make suggestions to peppy, I wonder if we could ask peppy to enable an option:
`Options -> Online -> Integration -> osu!direct: redownload beatmap immediately once osu link is received`

**Comment by omkelderman** [comment]
disclaimer: super random idea and I might be talking complete bullshit

Within /api/get_beatmaps of the api, there is the file_md5 thing, maybe that one can be used to check for new versions and if detected manually delete said song-folder and hope invoking osu!direct next time will download the map?

**Comment by RedbackThomson** [comment]
Using what libraries did you make this, Tillerino?

**Comment by Tillerino** [comment]
Uhm. I forgot the name. It's a bunch if wrappers around opencv. I stripped
away most of the layers, got rid of some redundancies and right now 80% of
the time is spent in opencv's matchTemplate function. One scan for all
relevant buttons takes a little over 300ms. This is more than I was
expecting. We need to discuss what at kind of interval we could run this.

**Comment by Tillerino** [comment]
Implemented and running.
